//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogwaiLauncher.WinApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gls.ddo.com/GLS.DataCenterServer/Service.asmx")]
        public string MogwaiLauncher_WinApp_Turbine_GLS_GLS_x0020_Datacenter_x0020_Info_x0020_Server {
            get {
                return ((string)(this["MogwaiLauncher_WinApp_Turbine_GLS_GLS_x0020_Datacenter_x0020_Info_x0020_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gls-auth.ddo.com/GLS.AuthServer/Service.asmx")]
        public string MogwaiLauncher_WinApp_Turbine_GLS_Auth_Global_x0020_Login_x0020_System_x0020_Authentication_x0020_Service {
            get {
                return ((string)(this["MogwaiLauncher_WinApp_Turbine_GLS_Auth_Global_x0020_Login_x0020_System_x0020_Auth" +
                    "entication_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gls.ddo.com/GLS.DataCenterServer/Service.asmx")]
        public string LocalLotroLauncher_WinApp_Turbine_GLS_GLS_x0020_Datacenter_x0020_Info_x0020_Server {
            get {
                return ((string)(this["LocalLotroLauncher_WinApp_Turbine_GLS_GLS_x0020_Datacenter_x0020_Info_x0020_Serve" +
                    "r"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gls-auth.ddo.com/GLS.AuthServer/Service.asmx")]
        public string LocalLotroLauncher_WinApp_Turbine_GLS_Auth_Global_x0020_Login_x0020_System_x0020_Authentication_x0020_Service {
            get {
                return ((string)(this["LocalLotroLauncher_WinApp_Turbine_GLS_Auth_Global_x0020_Login_x0020_System_x0020_" +
                    "Authentication_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Ams/AmsAccountManagement.asmx")]
        public string MogwaiLauncher_WinApp_AmsAccountManagement_AmsAccountManagement {
            get {
                return ((string)(this["MogwaiLauncher_WinApp_AmsAccountManagement_AmsAccountManagement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Ams/AmsSubscriptionManagement.asmx")]
        public string MogwaiLauncher_WinApp_AmsSubscriptionManagement_AmsSubscriptionManagement {
            get {
                return ((string)(this["MogwaiLauncher_WinApp_AmsSubscriptionManagement_AmsSubscriptionManagement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Ams/AmsAuthentication.asmx")]
        public string MogwaiLauncher_WinApp_AmsAuthentication_AmsAuthentication {
            get {
                return ((string)(this["MogwaiLauncher_WinApp_AmsAuthentication_AmsAuthentication"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Ams/AmsAccountManagement.asmx")]
        public string LocalLauncher_WinApp_AmsAccountManagement_AmsAccountManagement {
            get {
                return ((string)(this["LocalLauncher_WinApp_AmsAccountManagement_AmsAccountManagement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Ams/AmsAuthentication.asmx")]
        public string LocalLauncher_WinApp_AmsAuthentication_AmsAuthentication {
            get {
                return ((string)(this["LocalLauncher_WinApp_AmsAuthentication_AmsAuthentication"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Ams/AmsSubscriptionManagement.asmx")]
        public string LocalLauncher_WinApp_AmsSubscriptionManagement_AmsSubscriptionManagement {
            get {
                return ((string)(this["LocalLauncher_WinApp_AmsSubscriptionManagement_AmsSubscriptionManagement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gls.ddo.com/GLS.DataCenterServer/Service.asmx")]
        public string LocalLauncher_WinApp_Turbine_GLS_GLS_x0020_Datacenter_x0020_Info_x0020_Server {
            get {
                return ((string)(this["LocalLauncher_WinApp_Turbine_GLS_GLS_x0020_Datacenter_x0020_Info_x0020_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gls-auth.ddo.com/GLS.AuthServer/Service.asmx")]
        public string LocalLauncher_WinApp_Turbine_GLS_Auth_Global_x0020_Login_x0020_System_x0020_Authentication_x0020_Service {
            get {
                return ((string)(this["LocalLauncher_WinApp_Turbine_GLS_Auth_Global_x0020_Login_x0020_System_x0020_Authe" +
                    "ntication_x0020_Service"]));
            }
        }
    }
}
