//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MogwaiLauncher.WinApp.Turbine.GLS.Auth {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Global Login System Authentication ServiceSoap", Namespace="http://www.turbine.com/SE/GLS")]
    public partial class GlobalLoginSystemAuthenticationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback RefreshTicketOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GlobalLoginSystemAuthenticationService() {
            this.Url = global::MogwaiLauncher.WinApp.Properties.Settings.Default.LocalLauncher_WinApp_Turbine_GLS_Auth_Global_x0020_Login_x0020_System_x0020_Authentication_x0020_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginAccountCompletedEventHandler LoginAccountCompleted;
        
        /// <remarks/>
        public event RefreshTicketCompletedEventHandler RefreshTicketCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.turbine.com/SE/GLS/LoginAccount", RequestNamespace="http://www.turbine.com/SE/GLS", ResponseNamespace="http://www.turbine.com/SE/GLS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserProfile LoginAccount(string username, string password, string additionalInfo) {
            object[] results = this.Invoke("LoginAccount", new object[] {
                        username,
                        password,
                        additionalInfo});
            return ((UserProfile)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAccountAsync(string username, string password, string additionalInfo) {
            this.LoginAccountAsync(username, password, additionalInfo, null);
        }
        
        /// <remarks/>
        public void LoginAccountAsync(string username, string password, string additionalInfo, object userState) {
            if ((this.LoginAccountOperationCompleted == null)) {
                this.LoginAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginAccountOperationCompleted);
            }
            this.InvokeAsync("LoginAccount", new object[] {
                        username,
                        password,
                        additionalInfo}, this.LoginAccountOperationCompleted, userState);
        }
        
        private void OnLoginAccountOperationCompleted(object arg) {
            if ((this.LoginAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginAccountCompleted(this, new LoginAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.turbine.com/SE/GLS/RefreshTicket", RequestNamespace="http://www.turbine.com/SE/GLS", ResponseNamespace="http://www.turbine.com/SE/GLS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RefreshTicket(string ticket) {
            object[] results = this.Invoke("RefreshTicket", new object[] {
                        ticket});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RefreshTicketAsync(string ticket) {
            this.RefreshTicketAsync(ticket, null);
        }
        
        /// <remarks/>
        public void RefreshTicketAsync(string ticket, object userState) {
            if ((this.RefreshTicketOperationCompleted == null)) {
                this.RefreshTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRefreshTicketOperationCompleted);
            }
            this.InvokeAsync("RefreshTicket", new object[] {
                        ticket}, this.RefreshTicketOperationCompleted, userState);
        }
        
        private void OnRefreshTicketOperationCompleted(object arg) {
            if ((this.RefreshTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RefreshTicketCompleted(this, new RefreshTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class UserProfile {
        
        private GameSubscription[] subscriptionsField;
        
        private string ticketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GameSubscription[] Subscriptions {
            get {
                return this.subscriptionsField;
            }
            set {
                this.subscriptionsField = value;
            }
        }
        
        /// <remarks/>
        public string Ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class GameSubscription {
        
        private string gameField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string[] productTokensField;
        
        private string[] customerServiceTokensField;
        
        private string expirationDateField;
        
        private string statusField;
        
        private string nextBillingDateField;
        
        private string pendingCancelDateField;
        
        private string autoRenewField;
        
        private string billingSystemTimeField;
        
        private string additionalInfoField;
        
        /// <remarks/>
        public string Game {
            get {
                return this.gameField;
            }
            set {
                this.gameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string[] ProductTokens {
            get {
                return this.productTokensField;
            }
            set {
                this.productTokensField = value;
            }
        }
        
        /// <remarks/>
        public string[] CustomerServiceTokens {
            get {
                return this.customerServiceTokensField;
            }
            set {
                this.customerServiceTokensField = value;
            }
        }
        
        /// <remarks/>
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string NextBillingDate {
            get {
                return this.nextBillingDateField;
            }
            set {
                this.nextBillingDateField = value;
            }
        }
        
        /// <remarks/>
        public string PendingCancelDate {
            get {
                return this.pendingCancelDateField;
            }
            set {
                this.pendingCancelDateField = value;
            }
        }
        
        /// <remarks/>
        public string AutoRenew {
            get {
                return this.autoRenewField;
            }
            set {
                this.autoRenewField = value;
            }
        }
        
        /// <remarks/>
        public string BillingSystemTime {
            get {
                return this.billingSystemTimeField;
            }
            set {
                this.billingSystemTimeField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void LoginAccountCompletedEventHandler(object sender, LoginAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserProfile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserProfile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RefreshTicketCompletedEventHandler(object sender, RefreshTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RefreshTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RefreshTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591