//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MogwaiLauncher.WinApp.Turbine.GLS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GLS Datacenter Info ServerSoap", Namespace="http://www.turbine.com/SE/GLS")]
    public partial class GLSDatacenterInfoServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDatacentersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DumpCacheOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GLSDatacenterInfoServer() {
            this.Url = global::MogwaiLauncher.WinApp.Properties.Settings.Default.LocalLauncher_WinApp_Turbine_GLS_GLS_x0020_Datacenter_x0020_Info_x0020_Server;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDatacentersCompletedEventHandler GetDatacentersCompleted;
        
        /// <remarks/>
        public event ServerInfoCompletedEventHandler ServerInfoCompleted;
        
        /// <remarks/>
        public event DumpCacheCompletedEventHandler DumpCacheCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.turbine.com/SE/GLS/GetDatacenters", RequestNamespace="http://www.turbine.com/SE/GLS", ResponseNamespace="http://www.turbine.com/SE/GLS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Datacenter[] GetDatacenters(string game) {
            object[] results = this.Invoke("GetDatacenters", new object[] {
                        game});
            return ((Datacenter[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDatacentersAsync(string game) {
            this.GetDatacentersAsync(game, null);
        }
        
        /// <remarks/>
        public void GetDatacentersAsync(string game, object userState) {
            if ((this.GetDatacentersOperationCompleted == null)) {
                this.GetDatacentersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDatacentersOperationCompleted);
            }
            this.InvokeAsync("GetDatacenters", new object[] {
                        game}, this.GetDatacentersOperationCompleted, userState);
        }
        
        private void OnGetDatacentersOperationCompleted(object arg) {
            if ((this.GetDatacentersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDatacentersCompleted(this, new GetDatacentersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.turbine.com/SE/GLS/ServerInfo", RequestNamespace="http://www.turbine.com/SE/GLS", ResponseNamespace="http://www.turbine.com/SE/GLS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ServerInfo(string s) {
            object[] results = this.Invoke("ServerInfo", new object[] {
                        s});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ServerInfoAsync(string s) {
            this.ServerInfoAsync(s, null);
        }
        
        /// <remarks/>
        public void ServerInfoAsync(string s, object userState) {
            if ((this.ServerInfoOperationCompleted == null)) {
                this.ServerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServerInfoOperationCompleted);
            }
            this.InvokeAsync("ServerInfo", new object[] {
                        s}, this.ServerInfoOperationCompleted, userState);
        }
        
        private void OnServerInfoOperationCompleted(object arg) {
            if ((this.ServerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServerInfoCompleted(this, new ServerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.turbine.com/SE/GLS/DumpCache", RequestNamespace="http://www.turbine.com/SE/GLS", ResponseNamespace="http://www.turbine.com/SE/GLS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusServerResult[] DumpCache() {
            object[] results = this.Invoke("DumpCache", new object[0]);
            return ((StatusServerResult[])(results[0]));
        }
        
        /// <remarks/>
        public void DumpCacheAsync() {
            this.DumpCacheAsync(null);
        }
        
        /// <remarks/>
        public void DumpCacheAsync(object userState) {
            if ((this.DumpCacheOperationCompleted == null)) {
                this.DumpCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDumpCacheOperationCompleted);
            }
            this.InvokeAsync("DumpCache", new object[0], this.DumpCacheOperationCompleted, userState);
        }
        
        private void OnDumpCacheOperationCompleted(object arg) {
            if ((this.DumpCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DumpCacheCompleted(this, new DumpCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class Datacenter {
        
        private string nameField;
        
        private World[] worldsField;
        
        private string authServerField;
        
        private string patchServerField;
        
        private string launcherConfigurationServerField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public World[] Worlds {
            get {
                return this.worldsField;
            }
            set {
                this.worldsField = value;
            }
        }
        
        /// <remarks/>
        public string AuthServer {
            get {
                return this.authServerField;
            }
            set {
                this.authServerField = value;
            }
        }
        
        /// <remarks/>
        public string PatchServer {
            get {
                return this.patchServerField;
            }
            set {
                this.patchServerField = value;
            }
        }
        
        /// <remarks/>
        public string LauncherConfigurationServer {
            get {
                return this.launcherConfigurationServerField;
            }
            set {
                this.launcherConfigurationServerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class World {
        
        private string nameField;
        
        private string loginServerUrlField;
        
        private string chatServerUrlField;
        
        private string statusServerUrlField;
        
        private int orderField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string LoginServerUrl {
            get {
                return this.loginServerUrlField;
            }
            set {
                this.loginServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ChatServerUrl {
            get {
                return this.chatServerUrlField;
            }
            set {
                this.chatServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string StatusServerUrl {
            get {
                return this.statusServerUrlField;
            }
            set {
                this.statusServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class StatusServerResult {
        
        private System.DateTime lastUpdatedField;
        
        private string resultsField;
        
        private bool updatingField;
        
        private string serverNameField;
        
        /// <remarks/>
        public System.DateTime LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public string Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public bool Updating {
            get {
                return this.updatingField;
            }
            set {
                this.updatingField = value;
            }
        }
        
        /// <remarks/>
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetDatacentersCompletedEventHandler(object sender, GetDatacentersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDatacentersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDatacentersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Datacenter[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Datacenter[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ServerInfoCompletedEventHandler(object sender, ServerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DumpCacheCompletedEventHandler(object sender, DumpCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DumpCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DumpCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusServerResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusServerResult[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591