//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogwaiLauncher.WinApp.TurbineTransferService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://www.turbine.com/SE/DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MogwaiLauncher.WinApp.TurbineTransferService.TokenBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MogwaiLauncher.WinApp.TurbineTransferService.PointBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MogwaiLauncher.WinApp.TurbineTransferService.MigrateRequest))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenBalanceRequest", Namespace="http://www.wbie.com/Platform/Turbine/DataContracts")]
    [System.SerializableAttribute()]
    public partial class TokenBalanceRequest : MogwaiLauncher.WinApp.TurbineTransferService.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriptionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionKey {
            get {
                return this.SubscriptionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionKeyField, value) != true)) {
                    this.SubscriptionKeyField = value;
                    this.RaisePropertyChanged("SubscriptionKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PointBalanceRequest", Namespace="http://www.wbie.com/Platform/Turbine/DataContracts")]
    [System.SerializableAttribute()]
    public partial class PointBalanceRequest : MogwaiLauncher.WinApp.TurbineTransferService.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriptionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionKey {
            get {
                return this.SubscriptionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionKeyField, value) != true)) {
                    this.SubscriptionKeyField = value;
                    this.RaisePropertyChanged("SubscriptionKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllCharactersRequest", Namespace="http://www.wbie.com/Platform/Turbine/DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetAllCharactersRequest : MogwaiLauncher.WinApp.TurbineTransferService.BaseRequest {
        
        private string SubscriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Subscription {
            get {
                return this.SubscriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionField, value) != true)) {
                    this.SubscriptionField = value;
                    this.RaisePropertyChanged("Subscription");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MigrateRequest", Namespace="http://www.wbie.com/Platform/Turbine/DataContracts")]
    [System.SerializableAttribute()]
    public partial class MigrateRequest : MogwaiLauncher.WinApp.TurbineTransferService.BaseRequest {
        
        private string AccountField;
        
        private string GlsTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        private string SourceShardField;
        
        private string SubscriptionField;
        
        private string TargetShardField;
        
        private MogwaiLauncher.WinApp.TurbineTransferService.TransferItems TransferItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string GlsTicket {
            get {
                return this.GlsTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.GlsTicketField, value) != true)) {
                    this.GlsTicketField = value;
                    this.RaisePropertyChanged("GlsTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SourceShard {
            get {
                return this.SourceShardField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceShardField, value) != true)) {
                    this.SourceShardField = value;
                    this.RaisePropertyChanged("SourceShard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Subscription {
            get {
                return this.SubscriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionField, value) != true)) {
                    this.SubscriptionField = value;
                    this.RaisePropertyChanged("Subscription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TargetShard {
            get {
                return this.TargetShardField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetShardField, value) != true)) {
                    this.TargetShardField = value;
                    this.RaisePropertyChanged("TargetShard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MogwaiLauncher.WinApp.TurbineTransferService.TransferItems TransferItems {
            get {
                return this.TransferItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferItemsField, value) != true)) {
                    this.TransferItemsField = value;
                    this.RaisePropertyChanged("TransferItems");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferItems", Namespace="http://schemas.datacontract.org/2004/07/Turbine.Tts.Logic.Entities")]
    [System.SerializableAttribute()]
    public partial class TransferItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CharactersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Account {
            get {
                return this.AccountField;
            }
            set {
                if ((this.AccountField.Equals(value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Characters {
            get {
                return this.CharactersField;
            }
            set {
                if ((object.ReferenceEquals(this.CharactersField, value) != true)) {
                    this.CharactersField = value;
                    this.RaisePropertyChanged("Characters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://www.turbine.com/SE/DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MogwaiLauncher.WinApp.TurbineTransferService.GetTokenBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MogwaiLauncher.WinApp.TurbineTransferService.GetPointBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MogwaiLauncher.WinApp.TurbineTransferService.MigrateResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MogwaiLauncher.WinApp.TurbineTransferService.ApiError ApiErrorField;
        
        private bool HasErrorField;
        
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MogwaiLauncher.WinApp.TurbineTransferService.ApiError ApiError {
            get {
                return this.ApiErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ApiErrorField, value) != true)) {
                    this.ApiErrorField = value;
                    this.RaisePropertyChanged("ApiError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiError", Namespace="http://www.turbine.com/SE")]
    [System.SerializableAttribute()]
    public partial class ApiError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorArgumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MogwaiLauncher.WinApp.TurbineTransferService.ApiError InnerApiErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorArgument {
            get {
                return this.ErrorArgumentField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorArgumentField, value) != true)) {
                    this.ErrorArgumentField = value;
                    this.RaisePropertyChanged("ErrorArgument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorReason {
            get {
                return this.ErrorReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorReasonField, value) != true)) {
                    this.ErrorReasonField = value;
                    this.RaisePropertyChanged("ErrorReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorValue {
            get {
                return this.ErrorValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorValueField, value) != true)) {
                    this.ErrorValueField = value;
                    this.RaisePropertyChanged("ErrorValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MogwaiLauncher.WinApp.TurbineTransferService.ApiError InnerApiError {
            get {
                return this.InnerApiErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerApiErrorField, value) != true)) {
                    this.InnerApiErrorField = value;
                    this.RaisePropertyChanged("InnerApiError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType {
            get {
                return this.ObjectTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectTypeField, value) != true)) {
                    this.ObjectTypeField = value;
                    this.RaisePropertyChanged("ObjectType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTokenBalanceResponse", Namespace="http://www.wbie.com/Platform/Turbine/DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetTokenBalanceResponse : MogwaiLauncher.WinApp.TurbineTransferService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountEmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CharacterTransferTokenBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountEmailAddress {
            get {
                return this.AccountEmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountEmailAddressField, value) != true)) {
                    this.AccountEmailAddressField = value;
                    this.RaisePropertyChanged("AccountEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CharacterTransferTokenBalance {
            get {
                return this.CharacterTransferTokenBalanceField;
            }
            set {
                if ((this.CharacterTransferTokenBalanceField.Equals(value) != true)) {
                    this.CharacterTransferTokenBalanceField = value;
                    this.RaisePropertyChanged("CharacterTransferTokenBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPointBalanceResponse", Namespace="http://www.wbie.com/Platform/Turbine/DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetPointBalanceResponse : MogwaiLauncher.WinApp.TurbineTransferService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountEmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TokenBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountEmailAddress {
            get {
                return this.AccountEmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountEmailAddressField, value) != true)) {
                    this.AccountEmailAddressField = value;
                    this.RaisePropertyChanged("AccountEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointBalance {
            get {
                return this.PointBalanceField;
            }
            set {
                if ((this.PointBalanceField.Equals(value) != true)) {
                    this.PointBalanceField = value;
                    this.RaisePropertyChanged("PointBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TokenBalance {
            get {
                return this.TokenBalanceField;
            }
            set {
                if ((this.TokenBalanceField.Equals(value) != true)) {
                    this.TokenBalanceField = value;
                    this.RaisePropertyChanged("TokenBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllCharactersResponse", Namespace="http://www.wbie.com/Platform/Turbine/DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetAllCharactersResponse : MogwaiLauncher.WinApp.TurbineTransferService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MogwaiLauncher.WinApp.TurbineTransferService.CharactersOnShard[] ShardsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBanned {
            get {
                return this.IsBannedField;
            }
            set {
                if ((this.IsBannedField.Equals(value) != true)) {
                    this.IsBannedField = value;
                    this.RaisePropertyChanged("IsBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MogwaiLauncher.WinApp.TurbineTransferService.CharactersOnShard[] Shards {
            get {
                return this.ShardsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShardsField, value) != true)) {
                    this.ShardsField = value;
                    this.RaisePropertyChanged("Shards");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MigrateResponse", Namespace="http://www.wbie.com/Platform/Turbine/DataContracts")]
    [System.SerializableAttribute()]
    public partial class MigrateResponse : MogwaiLauncher.WinApp.TurbineTransferService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfullyQueuedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuccessfullyQueued {
            get {
                return this.SuccessfullyQueuedField;
            }
            set {
                if ((this.SuccessfullyQueuedField.Equals(value) != true)) {
                    this.SuccessfullyQueuedField = value;
                    this.RaisePropertyChanged("SuccessfullyQueued");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharactersOnShard", Namespace="http://schemas.datacontract.org/2004/07/Turbine.Tts.Logic.Entities")]
    [System.SerializableAttribute()]
    public partial class CharactersOnShard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MogwaiLauncher.WinApp.TurbineTransferService.Character[] CharactersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasAccountDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MogwaiLauncher.WinApp.TurbineTransferService.Shard ShardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MogwaiLauncher.WinApp.TurbineTransferService.Character[] Characters {
            get {
                return this.CharactersField;
            }
            set {
                if ((object.ReferenceEquals(this.CharactersField, value) != true)) {
                    this.CharactersField = value;
                    this.RaisePropertyChanged("Characters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAccountData {
            get {
                return this.HasAccountDataField;
            }
            set {
                if ((this.HasAccountDataField.Equals(value) != true)) {
                    this.HasAccountDataField = value;
                    this.RaisePropertyChanged("HasAccountData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MogwaiLauncher.WinApp.TurbineTransferService.Shard Shard {
            get {
                return this.ShardField;
            }
            set {
                if ((object.ReferenceEquals(this.ShardField, value) != true)) {
                    this.ShardField = value;
                    this.RaisePropertyChanged("Shard");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shard", Namespace="http://schemas.datacontract.org/2004/07/Turbine.Tts.Logic.Entities")]
    [System.SerializableAttribute()]
    public partial class Shard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Character", Namespace="http://schemas.datacontract.org/2004/07/Turbine.Tts.Logic.Entities")]
    [System.SerializableAttribute()]
    public partial class Character : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GuildLeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SavedTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GuildLeader {
            get {
                return this.GuildLeaderField;
            }
            set {
                if ((this.GuildLeaderField.Equals(value) != true)) {
                    this.GuildLeaderField = value;
                    this.RaisePropertyChanged("GuildLeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iid {
            get {
                return this.IidField;
            }
            set {
                if ((object.ReferenceEquals(this.IidField, value) != true)) {
                    this.IidField = value;
                    this.RaisePropertyChanged("Iid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Locked {
            get {
                return this.LockedField;
            }
            set {
                if ((this.LockedField.Equals(value) != true)) {
                    this.LockedField = value;
                    this.RaisePropertyChanged("Locked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SavedTimestamp {
            get {
                return this.SavedTimestampField;
            }
            set {
                if ((this.SavedTimestampField.Equals(value) != true)) {
                    this.SavedTimestampField = value;
                    this.RaisePropertyChanged("SavedTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subscription {
            get {
                return this.SubscriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionField, value) != true)) {
                    this.SubscriptionField = value;
                    this.RaisePropertyChanged("Subscription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTransferConfigurationResponse", Namespace="http://www.wbie.com/Platform/Turbine/DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetTransferConfigurationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentWaitTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Configuration {
            get {
                return this.ConfigurationField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigurationField, value) != true)) {
                    this.ConfigurationField = value;
                    this.RaisePropertyChanged("Configuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentWaitTime {
            get {
                return this.CurrentWaitTimeField;
            }
            set {
                if ((this.CurrentWaitTimeField.Equals(value) != true)) {
                    this.CurrentWaitTimeField = value;
                    this.RaisePropertyChanged("CurrentWaitTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TurbineTransferService.TurbineTransferService")]
    public interface TurbineTransferService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/Migrate", ReplyAction="http://tempuri.org/TurbineTransferService/MigrateResponse")]
        MogwaiLauncher.WinApp.TurbineTransferService.MigrateResponse Migrate(MogwaiLauncher.WinApp.TurbineTransferService.MigrateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/Migrate", ReplyAction="http://tempuri.org/TurbineTransferService/MigrateResponse")]
        System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.MigrateResponse> MigrateAsync(MogwaiLauncher.WinApp.TurbineTransferService.MigrateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/GetTransferConfiguration", ReplyAction="http://tempuri.org/TurbineTransferService/GetTransferConfigurationResponse")]
        MogwaiLauncher.WinApp.TurbineTransferService.GetTransferConfigurationResponse GetTransferConfiguration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/GetTransferConfiguration", ReplyAction="http://tempuri.org/TurbineTransferService/GetTransferConfigurationResponse")]
        System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.GetTransferConfigurationResponse> GetTransferConfigurationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/GetTokenBalance", ReplyAction="http://tempuri.org/TurbineTransferService/GetTokenBalanceResponse")]
        MogwaiLauncher.WinApp.TurbineTransferService.GetTokenBalanceResponse GetTokenBalance(MogwaiLauncher.WinApp.TurbineTransferService.TokenBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/GetTokenBalance", ReplyAction="http://tempuri.org/TurbineTransferService/GetTokenBalanceResponse")]
        System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.GetTokenBalanceResponse> GetTokenBalanceAsync(MogwaiLauncher.WinApp.TurbineTransferService.TokenBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/GetPointBalance", ReplyAction="http://tempuri.org/TurbineTransferService/GetPointBalanceResponse")]
        MogwaiLauncher.WinApp.TurbineTransferService.GetPointBalanceResponse GetPointBalance(MogwaiLauncher.WinApp.TurbineTransferService.PointBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/GetPointBalance", ReplyAction="http://tempuri.org/TurbineTransferService/GetPointBalanceResponse")]
        System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.GetPointBalanceResponse> GetPointBalanceAsync(MogwaiLauncher.WinApp.TurbineTransferService.PointBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/GetAllCharacters", ReplyAction="http://tempuri.org/TurbineTransferService/GetAllCharactersResponse")]
        MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersResponse GetAllCharacters(MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/GetAllCharacters", ReplyAction="http://tempuri.org/TurbineTransferService/GetAllCharactersResponse")]
        System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersResponse> GetAllCharactersAsync(MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/CreditTransferTokenBalance", ReplyAction="http://tempuri.org/TurbineTransferService/CreditTransferTokenBalanceResponse")]
        int CreditTransferTokenBalance(string subscriptionKey, int tokens);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurbineTransferService/CreditTransferTokenBalance", ReplyAction="http://tempuri.org/TurbineTransferService/CreditTransferTokenBalanceResponse")]
        System.Threading.Tasks.Task<int> CreditTransferTokenBalanceAsync(string subscriptionKey, int tokens);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TurbineTransferServiceChannel : MogwaiLauncher.WinApp.TurbineTransferService.TurbineTransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TurbineTransferServiceClient : System.ServiceModel.ClientBase<MogwaiLauncher.WinApp.TurbineTransferService.TurbineTransferService>, MogwaiLauncher.WinApp.TurbineTransferService.TurbineTransferService {
        
        public TurbineTransferServiceClient() {
        }
        
        public TurbineTransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TurbineTransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TurbineTransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TurbineTransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MogwaiLauncher.WinApp.TurbineTransferService.MigrateResponse Migrate(MogwaiLauncher.WinApp.TurbineTransferService.MigrateRequest request) {
            return base.Channel.Migrate(request);
        }
        
        public System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.MigrateResponse> MigrateAsync(MogwaiLauncher.WinApp.TurbineTransferService.MigrateRequest request) {
            return base.Channel.MigrateAsync(request);
        }
        
        public MogwaiLauncher.WinApp.TurbineTransferService.GetTransferConfigurationResponse GetTransferConfiguration() {
            return base.Channel.GetTransferConfiguration();
        }
        
        public System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.GetTransferConfigurationResponse> GetTransferConfigurationAsync() {
            return base.Channel.GetTransferConfigurationAsync();
        }
        
        public MogwaiLauncher.WinApp.TurbineTransferService.GetTokenBalanceResponse GetTokenBalance(MogwaiLauncher.WinApp.TurbineTransferService.TokenBalanceRequest request) {
            return base.Channel.GetTokenBalance(request);
        }
        
        public System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.GetTokenBalanceResponse> GetTokenBalanceAsync(MogwaiLauncher.WinApp.TurbineTransferService.TokenBalanceRequest request) {
            return base.Channel.GetTokenBalanceAsync(request);
        }
        
        public MogwaiLauncher.WinApp.TurbineTransferService.GetPointBalanceResponse GetPointBalance(MogwaiLauncher.WinApp.TurbineTransferService.PointBalanceRequest request) {
            return base.Channel.GetPointBalance(request);
        }
        
        public System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.GetPointBalanceResponse> GetPointBalanceAsync(MogwaiLauncher.WinApp.TurbineTransferService.PointBalanceRequest request) {
            return base.Channel.GetPointBalanceAsync(request);
        }
        
        public MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersResponse GetAllCharacters(MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersRequest request) {
            return base.Channel.GetAllCharacters(request);
        }
        
        public System.Threading.Tasks.Task<MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersResponse> GetAllCharactersAsync(MogwaiLauncher.WinApp.TurbineTransferService.GetAllCharactersRequest request) {
            return base.Channel.GetAllCharactersAsync(request);
        }
        
        public int CreditTransferTokenBalance(string subscriptionKey, int tokens) {
            return base.Channel.CreditTransferTokenBalance(subscriptionKey, tokens);
        }
        
        public System.Threading.Tasks.Task<int> CreditTransferTokenBalanceAsync(string subscriptionKey, int tokens) {
            return base.Channel.CreditTransferTokenBalanceAsync(subscriptionKey, tokens);
        }
    }
}
